### ISSUE TITLE
为什么只能播放一个视频？

### ISSUE THREAD

**Issue by DOSforever** [bergkamp/video-comparison-player#14]
点击“选取视频或图片”，选择了一个视频，该视频出现在左边窗口；再次点击“选取视频或图片”，选择了另一个视频，该视频出现在右边边窗口。但是点击上方的播放按钮只有右边的视频在播放，左边的没有播放。是我操作错误还是什么问题？

**Comment by bergkamp** [comment]
播放器是基于Chrome，没有集成其它特殊功能，有可能有些视频是不支持的，可以确认下左边那个视频用chrome能否播放。

**Comment by DOSforever** [comment]
基于 Chrome 的？我没有安装 Chrome 浏览器，而且我播放的是本地文件。使用其它 Blink 内核的浏览器如 Vivaldi , Edge 打开本地文件提示是保存、另存为、还是打开还是什么的，不能直接播放。
