### ISSUE TITLE
这个软件还更新不，希望支持拖拽视频功能

### ISSUE THREAD

**Issue by water110** [bergkamp/video-comparison-player#18]
支持往左边或者右边拖进来视频直接播放，现在只能点击左上角按钮选择对应视频，有时像替换其中一个，也必须选择两次，没办法指定替换哪边的，拖拽文件进来播放更方便，可参考这个：https://video-compare.kkk.plus/cn/online-video-compare，https://github.com/vzhd1701/gridplayer/

**Comment by bergkamp** [comment]
更，这个提议不错，但目前没有具体更新计划
